### ISSUE TITLE
[TLSInterception] Allow overriding path to `openssl` binary

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#1147]
Got it to work by replacing `'openssl'` by `'D:\\Program Files\\OpenSSL-Win64\\bin\\openssl.exe'`. After doing this in the pki.py file, the script runs fine :) 

The interception works, and the responses are cached correctly using the CacheResponsesPlugin. However, I did notice that some different errors are still created from time to time, but that doesn't seem to impact the websites that I am proxying that badly on first sight. `[WinError 10053] An established connection was aborted by the software in your host machine`

It says it aborted the connection, but after that it still seems to load the website eitherway and caches the response. (Presumably different HTTP requests)

```
2022-05-11 08:13:42,101 - pid:4252 [I] server.access_log:384 - 127.0.0.1:3909 - CONNECT www.example.com:443 - 0 bytes - 237.09ms 
2022-05-11 08:13:42,222 - pid:25156 [E] server.wrap_client:847 - OSError when wrapping client for upstream: www.example.com
Traceback (most recent call last):
File "D:\Python39\lib\site-packages\proxy\http\proxy\server.py", line 800, in wrap_client
self.client.wrap(self.flags.ca_signing_key_file, generated_cert)
File "D:\Python39\lib\site-packages\proxy\core\connection\client.py", line 45, in wrap
self._conn = ssl.wrap_socket(
File "D:\Python39\lib\ssl.py", line 1405, in wrap_socket
return context.wrap_socket(
File "D:\Python39\lib\ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "D:\Python39\lib\ssl.py", line 1040, in _create
self.do_handshake()
File "D:\Python39\lib\ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2022-05-11 08:13:42,224 - pid:25156 [I] server.access_log:384 - 127.0.0.1:3908 - CONNECT www.example.com:443 - 0 bytes - 357.61ms

...

2022-05-11 08:13:48,863 - pid:17268 [I] cache_responses.write_content_type:128 - Cached content file at C:\Users\xxx\.proxy\cache\content\www.example.com-e46611dab202487aa1b9cb257757d0d4.javascript
2022-05-11 08:13:48,884 - pid:10028 [I] server.access_log:384 - 127.0.0.1:3896 - CONNECT www.example.com:443 - 469 bytes - 7838.14ms
2022-05-11 08:13:48,929 - pid:10028 [I] cache_responses.write_content_type:128 - Cached content file at C:\Users\xxx\.proxy\cache\content\www.example.com-9d31702cdd7b4f12a3f2eae9ee306b97.html
```

Not sure whether this is a big deal, but thought I would mention it just in case.

_Originally posted by @KeanuNys in https://github.com/abhinavsingh/proxy.py/issues/1146#issuecomment-1123242564_

**Comment by abhinavsingh** [comment]
@KeanuNys PR https://github.com/abhinavsingh/proxy.py/pull/1257 will add ability to override path to openssl binary using the `--openssl` flag.  Thanks again for reporting this.
