### ISSUE TITLE
[HttpParser] Handle invalid/malformed request chunks from client

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#127]
**Describe the bug**
Currently, `HttpParser` works well assuming incoming client is not notorious :)  Handle cases when client can send invalid chunks in requests.

**To Reproduce**
1. Run `proxy.py` as `proxy.py --pac-file proxy.pac`
2. `telnet localhost 8899` and hit `Enter` key to send line feed
```
$ telnet localhost 8899
Trying ::1...
Connected to localhost.
Escape character is '^]'.

Connection closed by foreign host.
```
3. See error

```
2019-10-11 11:12:06,277 - pid:55396 [E] run:2215 - Exception while handling connection <socket.socket fd=27, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 8899, 0, 0), raddr=('::1', 49902, 0, 0)>
Traceback (most recent call last):
  File "./proxy.py", line 2205, in run
    teardown = self.run_once()
  File "./proxy.py", line 2173, in run_once
    teardown = self.handle_events(readables, writables)
  File "./proxy.py", line 2138, in handle_events
    teardown = self.handle_readables(readables)
  File "./proxy.py", line 2076, in handle_readables
    self.request.parse(client_data)
  File "./proxy.py", line 615, in parse
    more, raw = self.process(raw)
  File "./proxy.py", line 625, in process
    self.process_line(line)
  File "./proxy.py", line 667, in process_line
    self.url = urlparse.urlsplit(line[1])
IndexError: list index out of range
2019-10-11 11:12:06,279 - pid:55396 [I] access_log:1955 - ::1:49902 -  None
```

**Expected behavior**
`HttpParser` must either ignore invalid chunks or be strict about it and drop the connection.

**Comment by abhinavsingh** [comment]
Can also be triggered when parsing responses.  Following stack trace seen while TLS interception was enabled on a pipelined HTTPS connection.  Server seems to be sending us chunked packets without a prior chunked encoding header, which confuses our response parser.   Unsure if reason is similar for above stack trace seen when parsing requests.

```
2019-10-15 16:53:14,598 - pid:62085 [E] run:2674 - Exception while handling connection <ssl.SSLSocket fd=32, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 8899, 0, 0), raddr=('::1', 56549, 0, 0)>
Traceback (most recent call last):
  File "./proxy.py", line 2664, in run
    teardown = self.run_once()
  File "./proxy.py", line 2649, in run_once
    teardown = self.handle_events(readables, writables)
  File "./proxy.py", line 2465, in handle_events
    teardown = plugin.read_from_descriptors(readables)
  File "./proxy.py", line 1520, in read_from_descriptors
    self.pipeline_response.parse(raw)
  File "./proxy.py", line 670, in parse
    more, raw = self.process(raw)
  File "./proxy.py", line 680, in process
    self.process_line(line)
  File "./proxy.py", line 726, in process_line
    self.code = line[1]
IndexError: list index out of range
```

**Comment by abhinavsingh** [comment]
While response side fixes were addressed, request parsing still needs a fix.  With threadless execution here is the stacktrace with that telnet trick:

```
Process Threadless-6:1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "./proxy.py", line 1022, in run
    self.run_once()
  File "./proxy.py", line 1012, in run_once
    self.loop.run_until_complete(self.wait_for_tasks(tasks))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "./proxy.py", line 958, in wait_for_tasks
    teardown = await asyncio.wait_for(tasks[work_id], DEFAULT_TIMEOUT)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "./proxy.py", line 950, in handle_events
    return self.works[fileno].handle_events(readables, writables)
  File "./proxy.py", line 2484, in handle_events
    teardown = self.handle_readables(readables)
  File "./proxy.py", line 2631, in handle_readables
    self.request.parse(client_data)
  File "./proxy.py", line 687, in parse
    more, raw = self.process(raw)
  File "./proxy.py", line 697, in process
    self.process_line(line)
  File "./proxy.py", line 740, in process_line
    self.set_url(line[1])
IndexError: list index out of range
```

**Comment by abhinavsingh** [comment]
```
Exception while receiving from server connection <socket.socket fd=45, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2601:647:4281:2930:8870:ae4b:1b18:d18a', 51789, 0, 0)> with reason OSError(65, 'No route to host')
Traceback (most recent call last):
  File "./proxy.py", line 1530, in read_from_descriptors
    raw = self.server.recv(self.config.server_recvbuf_size)
  File "./proxy.py", line 436, in recv
    data: bytes = self.connection.recv(buffer_size)
OSError: [Errno 65] No route to host
```
