### ISSUE TITLE
FileNotFoundError when using ReverseProxyBasePlugin to forward requests to FastAPI application

### ISSUE THREAD

**Issue by creaexo** [abhinavsingh/proxy.py#1483]
**Check FAQs**
I didn't find the information necessary for this problem in the FAQ. But I found a [slightly similar issue](https://github.com/abhinavsingh/proxy.py/discussions/1330) in the discussions

**Describe the bug**
I wrote the simplest FastAPI application and a plugin based on the Reverse Proxy Base Plugin, which should redirect requests coming to the proxy server to the FastAPI application.  But when I make a request to the proxy, an error message appears in the terminal. If I try to make a request using the "/docs" path in the FastAPI application, it takes tens of minutes to wait for a response...

#### FastAPI
```python
# app.py
import uvicorn
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}

if __name__ == '__main__':
    uvicorn.run(app, host="127.8.8.8", port=8888)

```
#### Plugin
```python
# prox/redirector.py
from typing import Union, List, Tuple

from proxy.common.types import RePattern
from proxy.http import Url
from proxy.http.parser import HttpParser
from proxy.http.server import ReverseProxyBasePlugin


class MyReverse(ReverseProxyBasePlugin):

    def routes(self) -> List[Union[str, Tuple[str, List[bytes]]]]:
        return [r'/']

    def handle_route(
        self,
        request: HttpParser,
        pattern: RePattern,
    ) -> Union[memoryview, Url, 'TcpServerConnection']:
        return Url.from_bytes(b'http://127.8.8.8:8888' + request.path)

```

**To Reproduce**
1. Run FastAPI app `python3 app.py`:

2. Run `proxy.py` as `PYTHONPATH=/home/ubuntu/PycharmProjects/jupyterhub-fastapi-server .venv/bin/proxy --enable-reverse-proxy --plugins prox.redirector.MyReverse --hostname 127.5.5.5 --port 8000`

3. Do request in Googel Chrome `http://127.5.5.5:8000/`
4. See expected `{"message":"Hello World"}` in Browser and error in terminal
#### proxy.py
```
2024-09-25 19:19:48,783 - pid:55107 [I] plugins.load:89 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2024-09-25 19:19:48,783 - pid:55107 [I] plugins.load:89 - Loaded plugin proxy.http.server.HttpWebServerPlugin
2024-09-25 19:19:48,784 - pid:55107 [I] plugins.load:89 - Loaded plugin proxy.http.server.reverse.ReverseProxy
2024-09-25 19:19:48,784 - pid:55107 [I] plugins.load:89 - Loaded plugin prox.redirector.MyReverse
2024-09-25 19:19:52,983 - pid:55118 [E] base_events.default_exception_handler:1785 - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Threadless._run_forever() done, defined at /home/ubuntu/PycharmProjects/jupyterhub-fastapi-server/.venv/lib/python3.11/site-packages/proxy/core/work/threadless.py:386> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/jupyterhub-fastapi-server/.venv/lib/python3.11/site-packages/proxy/core/work/threadless.py", line 390, in _run_forever
    if await self._run_once():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/PycharmProjects/jupyterhub-fastapi-server/.venv/lib/python3.11/site-packages/proxy/core/work/threadless.py", line 349, in _run_once
    work_by_ids, new_work_available = await self._selected_events()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/PycharmProjects/jupyterhub-fastapi-server/.venv/lib/python3.11/site-packages/proxy/core/work/threadless.py", line 261, in _selected_events
    await self._update_selector()
  File "/home/ubuntu/PycharmProjects/jupyterhub-fastapi-server/.venv/lib/python3.11/site-packages/proxy/core/work/threadless.py", line 240, in _update_selector
    await self._update_work_events(work_id)
  File "/home/ubuntu/PycharmProjects/jupyterhub-fastapi-server/.venv/lib/python3.11/site-packages/proxy/core/work/threadless.py", line 161, in _update_work_events
    self.selector.modify(
  File "/usr/lib/python3.11/selectors.py", line 389, in modify
    self._selector.modify(key.fd, selector_events)
FileNotFoundError: [Errno 2] No such file or directory

```
#### app.py
```
INFO:     Started server process [54905]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.8.8.8:8888 (Press CTRL+C to quit)
INFO:     127.0.0.1:40116 - "GET / HTTP/1.1" 200 OK
```

**Expected behavior**
Instead errors see kinda:
```
2024-09-25 19:41:37,212 - pid:56764 [I] plugins.load:89 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2024-09-25 19:41:37,212 - pid:56764 [I] plugins.load:89 - Loaded plugin proxy.http.server.HttpWebServerPlugin
2024-09-25 19:41:37,212 - pid:56764 [I] plugins.load:89 - Loaded plugin proxy.http.server.reverse.ReverseProxy
2024-09-25 19:41:37,212 - pid:56764 [I] plugins.load:89 - Loaded plugin prox.redirector.MyReverse
2024-09-25 19:41:40,042 - pid:56767 [I] reverse.on_access_log:169 - 127.0.0.1:59164 - GET / - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 -> http://127.8.8.8:8888/ - 1.92ms
```

**Version information**
 - OS: Ubuntu 22.04.4 LTS
 - Browser Google Chrome
 - Device: PC
 - proxy.py Version 2.4.8

**Comment by abhinavsingh** [comment]
@creaexo Thank you for reporting, will take a look at this in coming days.

**Comment by abhinavsingh** [comment]
## My custom reverse proxy plugin code

```
from typing import TYPE_CHECKING, List, Tuple, Union

from proxy.http import Url
from proxy.http.parser import HttpParser
from proxy.http.server import ReverseProxyBasePlugin
from proxy.common.types import RePattern


if TYPE_CHECKING:
    from ..core.connection import TcpServerConnection


class MyReverse(ReverseProxyBasePlugin):

    def routes(self) -> List[Union[str, Tuple[str, List[bytes]]]]:
        return [r"/$"]

    def handle_route(
        self,
        request: HttpParser,
        pattern: RePattern,
    ) -> Union[memoryview, Url, "TcpServerConnection"]:
        assert request.path
        url = b"http://127.0.0.1:8888" + request.path
        return Url.from_bytes(url)
```

## FastApi app.py

```
import uvicorn
from fastapi import FastAPI


app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8888)
```

## Start app

```
python app.py                                                                                                                                                                        ─╯
INFO:     Started server process [89151]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)

INFO:     127.0.0.1:58858 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:58880 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:58924 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:59148 - "GET / HTTP/1.1" 200 OK
```

## Start proxy

```
proxy --log-level d --enable-reverse-proxy --plugins proxy.plugin.MyReverse --rewrite-host-header
```

## Try it

```
curl -v localhost:8899                            ─╯
* Host localhost:8899 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8899...
* connect to ::1 port 8899 from ::1 port 58856 failed: Connection refused
*   Trying 127.0.0.1:8899...
* Connected to localhost (127.0.0.1) port 8899
> GET / HTTP/1.1
> Host: localhost:8899
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Sat, 19 Oct 2024 12:33:51 GMT
< server: uvicorn
< content-length: 25
< content-type: application/json
< 
* Connection #0 to host localhost left intact
{"message":"Hello World"}% 
```

Seems to be doing the expected.

## Notes

1) I had to change `127.8.8.8` to `127.0.0.1` for both app.py and proxy
2) If you have `127.8.8.8` and `127.5.5.5`, please make sure both networks can reach each other

Let me know.

**Comment by abhinavsingh** [comment]
Closing this for now, please reopen if issue continues to persist.   I tested this on my MacOS, but there is no reason this will not work on Ubuntu etc.   Please let me know how it goes.
