### ISSUE TITLE
Unable to load any plugin

### ISSUE THREAD

**Issue by deeplook** [abhinavsingh/proxy.py#161]
I have pip-installed v. 1.1.1 on macOS in a conda environment, but when using any plugin like with `proxy.py --plugins plugin_examples.RedirectToCustomServerPlugin` (with or without `--enable-web-server`) I get the traceback below. Any idea?

```
2019-11-11 22:01:36,756 - pid:11619 [I] load_plugins:2427 - Loaded plugin proxy.HttpProxyPlugin
Traceback (most recent call last):
  File "/Users/gherman/Desktop/localdev/environments/basic/bin/proxy.py", line 2738, in <module>
    main(sys.argv[1:])  # pragma: no cover
  File "/Users/gherman/Desktop/localdev/environments/basic/bin/proxy.py", line 2707, in main
    (default_plugins, args.plugins)))
  File "/Users/gherman/Desktop/localdev/environments/basic/bin/proxy.py", line 2417, in load_plugins
    importlib.import_module(module_name),
  File "/Users/gherman/Desktop/localdev/environments/basic/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugin_examples'
```

**Comment by abhinavsingh** [comment]
@deeplook This gives some background https://github.com/abhinavsingh/proxy.py#unable-to-load-custom-plugins.  As the error says, there is `No module named 'plugin_examples'`.  Plugin examples are not shipped with `proxy.py` pip package.

A [work is in-progress](https://github.com/abhinavsingh/proxy.py/issues/156) to create separate pip package called `proxy.py-plugins`, which will install plugins so that they are discoverable.

For now, you'll have to clone or [download](https://github.com/abhinavsingh/proxy.py/archive/master.zip) the repository and then:

- Extract it
- Ensure plugins_example is discoverable
   - Either, `cd` into the extracted archive folder and then run again OR
   - OR, `PYTHONPATH=/path/to/extracted/folder proxy.py .....`

**Comment by deeplook** [comment]
I had read that section, but I thought it would apply only to "custom" plugins, as the name implies, believing that custom plugins would be my own or third-party ones while those mentioned in various examples would be "built-in" ones. Sorry for that, if I took it too literally. ;)

**Comment by abhinavsingh** [comment]
@deeplook No worries.  I should update the `FAQ` title to avoid confusion :)

Note that I provided download link to `master` branch, which is equivalent to `pip` latest version.  Under `develop` branch (default), `proxy.py` has moved to version `2.x` and is ~no longer single file~.
