### ISSUE TITLE
Handle cases when http traffic is received on https port for stats, dashboard and user warning

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#168]
```
ssl.SSLError
Traceback (most recent call last):
  File "/Users/abhinav/Dev/proxy.py/proxy/core/threadless.py", line 184, in accept_client
    self.works[fileno].initialize()
  File "/Users/abhinav/Dev/proxy.py/proxy/http/handler.py", line 131, in initialize
    conn = self.optionally_wrap_socket(self.client.connection)
  File "/Users/abhinav/Dev/proxy.py/proxy/http/handler.py", line 254, in optionally_wrap_socket
    server_side=True,
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
```

In theory, `proxy.py` can handle both `http` and `https` traffic over same port, but that won't be recommended from user experience POV.

**Comment by abhinavsingh** [comment]
Little did I realize that SSLError also shutdown the socket connection.  Nothing much that we can do here then.  Closing for now.
