### ISSUE TITLE
Exception if event unsubscribe request is received before subscribe

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#175]
**Describe the bug**
Exception if event unsubscribe request is received before subscribe.

**To Reproduce**
1. Run `proxy.py` as with dashboard enable
2. Go to inspect traffic tab.
3. Hit refresh

```
Process Threadless-3:1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/abhinav/Dev/proxy.py/proxy/core/threadless.py", line 233, in run
    self.run_once()
  File "/Users/abhinav/Dev/proxy.py/proxy/core/threadless.py", line 223, in run_once
    self.loop.run_until_complete(self.wait_for_tasks(tasks))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/abhinav/Dev/proxy.py/proxy/core/threadless.py", line 162, in wait_for_tasks
    teardown = await asyncio.wait_for(tasks[work_id], DEFAULT_TIMEOUT)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/Users/abhinav/Dev/proxy.py/proxy/core/threadless.py", line 153, in handle_events
    return self.works[fileno].handle_events(readables, writables)
  File "/Users/abhinav/Dev/proxy.py/proxy/http/handler.py", line 194, in handle_events
    teardown = self.handle_readables(readables)
  File "/Users/abhinav/Dev/proxy.py/proxy/http/handler.py", line 336, in handle_readables
    client_data)
  File "/Users/abhinav/Dev/proxy.py/proxy/http/server.py", line 274, in on_client_data
    route.on_websocket_message(frame)
  File "/Users/abhinav/Dev/proxy.py/dashboard/dashboard.py", line 98, in on_websocket_message
    self.subscriber.unsubscribe()
  File "/Users/abhinav/Dev/proxy.py/proxy/core/event.py", line 188, in unsubscribe
    assert self.relay_thread
AssertionError
```

**Comment by abhinavsingh** [comment]
Fixed with #188
