### ISSUE TITLE
[Threadless] Manager OSError with TLS interception

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#369]
This only happens when running under `--threadless` mode

**To Reproduce**
1. Run `proxy.py` with `--ca-key-file ca-key.pem --ca-cert-file ca-cert.pem --ca-signing-key ca-signing-key.pem --ca-file venv373/lib/python3.7/site-packages/certifi/cacert.pem --threadless --enable-dashboard --num-workers 1`
2. Do `browse few websites` to trigger error

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py", line 217, in handle_request
    c.close()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 177, in close
    self._close()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
```

**Expected behavior**
No exceptions

**Version information**
 - OS: MacOS
 - Browser: Chrome
 - Device: Macbook
 - Version: develop

**Comment by abhinavsingh** [comment]
Unable to reproduce it locally now, running with following flags:

```console
$ python -m proxy \
    --timeout 60 \
    --plugins proxy.plugin.CloudflareDnsResolverPlugin \
    --threadless \
    --hostname 127.0.0.1 \
    --enable-dashboard \
    --ca-key-file ca-key.pem \
    --ca-cert-file ca-cert.pem \
    --ca-signing-key ca-signing-key.pem \
    --ca-file venv310/lib/python3.10/site-packages/certifi/cacert.pem 
```

Will keep running on TLS interception for a few days to surface any issues.  Will re-open if `Manager` OSError is encountered again.
