### ISSUE TITLE
[TLSInterception] OSError when wrapping client

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#371]
**To Reproduce**
1. Run `proxy.py` with TLS Interception ON
2. Occasionally will result in `OSError` during client wrap

```
Traceback (most recent call last):
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 289, in on_request_complete
    self.wrap_client()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 463, in wrap_client
    ssl_version=ssl.PROTOCOL_TLSv1_2)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1222, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1056)
```

**Comment by abhinavsingh** [comment]
Above exception then manifests into

```
Exception ignored in: <function _ConnectionBase.__del__ at 0x104d777b8>
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 132, in __del__
    self._close()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
```

**Comment by abhinavsingh** [comment]
Following exception stacktrace has also been observed in the wild:

```
OSError when wrapping client
Traceback (most recent call last):
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 289, in on_request_complete
    self.wrap_client()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 463, in wrap_client
    keyfile=self.flags.ca_signing_key_file)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1222, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 832, in _create
    self.getpeername()
OSError: [Errno 22] Invalid argument
```

**Comment by abhinavsingh** [comment]
Another exception encountered due to failing `openssl` command

```
[E] run:340 - Exception while handling connection <socket.socket fd=105, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 8899, 0, 0), raddr=('::1', 59080, 0, 0)>
Traceback (most recent call last):
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 330, in run
    teardown = self.run_once()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 315, in run_once
    teardown = self.handle_events(readables, writables)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 118, in handle_events
    teardown = self.handle_readables(readables)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 274, in handle_readables
    upgraded_sock = plugin.on_request_complete()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 289, in on_request_complete
    self.wrap_client()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 461, in wrap_client
    cast(Dict[str, Any], self.server.connection.getpeercert()))
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 441, in generate_upstream_certificate
    self.gen_ca_signed_certificate(cert_file_path, certificate)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 398, in gen_ca_signed_certificate
    assert(resp is True)
AssertionError
Exception in thread Thread-79:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 342, in run
    self.shutdown()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 133, in shutdown
    self.flush()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 188, in flush
    selectors.EVENT_WRITE)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/selectors.py", line 517, in register
    key = super().register(fileobj, events, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/selectors.py", line 242, in register
    .format(fileobj, key.fd))
KeyError: "<socket.socket fd=105, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 8899, 0, 0), raddr=('::1', 59080, 0, 0)> (FD 105) is already registered"
```

**Comment by paul-alkhimov** [comment]
I have similar situation.
In my case the line `self.server._conn = ctx.wrap_socket(self.server.connection, server_hostname=hostname)` in server.py throws something like "ssl wrong version" and then in turn in handler.py in `shutdown()` -> `flush()` -> `self.selector.register(self.client.connection, selectors.EVENT_WRITE)` I get the exception which you have.
I haven't figured out yet how exactly the socket (fd=105 in your case) is expected to be correctly `select`ed.

**Comment by abhinavsingh** [comment]
@paul-alkhimov Yes this only happen when TLS Interception is ON.

`ssl wrong version` is a new case compared to those reported above.  I suspect it is due to old SSL/TLS versions and/or invalid certificates.  In my observation, this only happen with selected few sites.

Let's keep this open. I would love to add clean handling of these exceptions to start with.  Unsure if we can fix them all though.

**Comment by arunpalaniappan** [comment]
I get this error each time when I run with TLS Interception in ON.

I used the certificates generates by `make ca-certificates` as well as generating my own certificates with `openssl`. The error occurred in both cases and it occurs with all websites.

```
2021-05-03 17:55:33,209 - pid:57264 [E] intercept:539 - OSError when wrapping client
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.8/site-packages/proxy/http/proxy/server.py", line 529, in intercept
    self.wrap_client()
  File "/home/arun/.local/lib/python3.8/site-packages/proxy/http/proxy/server.py", line 559, in wrap_client
    self.client.wrap(self.flags.ca_signing_key_file, generated_cert)
  File "/home/arun/.local/lib/python3.8/site-packages/proxy/core/connection/client.py", line 37, in wrap
    self._conn = ssl.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 1402, in wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:4043)
```

I checked whether there is mismatch in key values by looking at the modulus value of keys, but there is not key mismatch error. I use openssl version 1.1.1f in an Ubuntu 20.04.1 LTS machine.

Any help on where to start for fixing the bug will be useful. Thanks.

**Comment by hash3liZer** [comment]
Pretty much the same error even for now. Any updates on this one so far? @abhinavsingh Or any idea where specifically to look for the error?

**Comment by abhinavsingh** [comment]
Hi @hash3liZer , apologies, I have been away from the project for too long now, stuck on some other project.

But i'll try and revisit this in coming week to make sure things are working fine e2e.  I haven't looked at this error, or if I did, I cannot recall what I found.  Will try again.

I will ask questions if I am unable to reproduce it.  Or if you know how to definitely reproduce this error, kindly let me know in comments.

**Comment by hash3liZer** [comment]
Okay, so i am not very much expert with tls interception and encryption. However, upon debugging `proxy.py`, i found out that `KEY_VALUES_MISMATCH` occurs when the keys in `cert.pem` and `key.pem` doesn't match. Which can be verified using command: 

```
$ openssl x509 -noout -modulus -in cert.pem
$ openssl rsa -noout -modulus -in key.pem
```

Which i verified and both the keys match. So, the key and certificates are both fine. However, when the `ssl.wrap_socket` function is called in the function named : `wrap` in file: `proxy\core\connection\client.py`. The certfile used to wrap the socket is of the website being currently visited which is located under directory: `.proxy/certificates` . 

And for sure, the key from that certificate won't match our private key. Thats why the error: `KEY_VALUES_MISMATCH`. How to fix it. I mean how to make sure that proxy.py supplies the correct certificate to the `wrap` function.

**Comment by hash3liZer** [comment]
Hey  @abhinavsingh . Thanks for replying mate. Sure, i will explain how to reproduce it: 
Tested on : `Windows 10 Pro with OpenSSL x86 v1.1.1`

Generate Certificate and private keys: 
```
make ca-certificates
```

Start in TLS interception mode:
```
$ proxy \
    --plugins proxy.plugin.CacheResponsesPlugin \
    --ca-key-file ca-key.pem \
    --ca-cert-file ca-cert.pem \
    --ca-signing-key-file ca-signing-key.pem
```

Install `ca-cert.pem` in your browser for firefox or in your root certificate authority for chrome. Setup proxy in your browser and visit and site and you will get this error: 

```
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.8/site-packages/proxy/http/proxy/server.py", line 529, in intercept
    self.wrap_client()
  File "/home/arun/.local/lib/python3.8/site-packages/proxy/http/proxy/server.py", line 559, in wrap_client
    self.client.wrap(self.flags.ca_signing_key_file, generated_cert)
  File "/home/arun/.local/lib/python3.8/site-packages/proxy/core/connection/client.py", line 37, in wrap
    self._conn = ssl.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 1402, in wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:4043)
```

**Comment by hash3liZer** [comment]
OK, so after like 3 days of continuous on screen time, i finally solved it. The error occured because `proxy.py` was validating the key against old certificates from the system. I simply had to remove those certificates and it worked like a charm. How to make it work: 

Remove `.proxy` directory under home directory: 
```
$ rm -rf /home/hash3liZer/.root
```

And generate certificates:
```
$ make ca-certificates
```

And run it as usual:
```
$ proxy.py --ca-cert ca-cert.pem --ca-key ca-key.pem --ca-signing-key-file ca-signing-key.pem
```

**Comment by abhinavsingh** [comment]
@hash3liZer I came back to it today, glad this is resolved now.  Won't have guessed it.  Will keep this open and add this to `FAQ` section.

**Comment by abhinavsingh** [comment]
@hash3liZer Thanks again for reporting this and for the resolution.  This indeed can happen for long running instances as generated certificates may expire or get invalidates.  I have repurposed this issue to keep a track of issue with old certificates.  Thank you!!!

**Comment by abhinavsingh** [comment]
Opened another issue as this one contains too many mixed contexts.  Some of these Exception issues with TLS interception are now resolved.  Also see, https://github.com/abhinavsingh/proxy.py#oserror-when-wrapping-client-for-tls-interception FAQ section for more details.

- See #731
