### ISSUE TITLE
[TLSInterception] Handle TimeoutExpired exception during certificate generation

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#389]
**To Reproduce**
1. Run `proxy.py` with TLS Interception enabled
2. By default `proxy.py` uses 10 second as timeout for `openssl` commands.  However, sometimes this limit may exceed, resulting into following exception:

```
2020-07-04 12:25:55,006 - pid:48280 [E] run:340 - Exception while handling connection <socket.socket fd=156, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 8899, 0, 0), raddr=('::1', 54340, 0, 0)>
Traceback (most recent call last):
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 330, in run
    teardown = self.run_once()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 315, in run_once
    teardown = self.handle_events(readables, writables)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 118, in handle_events
    teardown = self.handle_readables(readables)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 274, in handle_readables
    upgraded_sock = plugin.on_request_complete()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 289, in on_request_complete
    self.wrap_client()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 456, in wrap_client
    cast(Dict[str, Any], self.server.connection.getpeercert()))
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 436, in generate_upstream_certificate
    self.gen_ca_signed_certificate(cert_file_path, certificate)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/proxy/server.py", line 402, in gen_ca_signed_certificate
    crt_path=public_key_path, timeout=timeout)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/common/pki.py", line 122, in gen_csr
    return run_openssl_command(command, timeout)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/common/pki.py", line 216, in run_openssl_command
    cmd.communicate(timeout=timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1682, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 982, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['openssl', 'x509', '-x509toreq', '-passin', 'pass:', '-in', '/Users/abhinavsingh/.proxy/certificates/api.www.s81c.com.pub', '-signkey', 'ca-signing-key.pem', '-out', '/Users/abhinavsingh/.proxy/certificates/api.www.s81c.com.csr']' timed out after 10 seconds
Exception in thread Thread-105:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 342, in run
    self.shutdown()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 133, in shutdown
    self.flush()
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/handler.py", line 188, in flush
    selectors.EVENT_WRITE)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/selectors.py", line 517, in register
    key = super().register(fileobj, events, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/selectors.py", line 242, in register
    .format(fileobj, key.fd))
KeyError: "<socket.socket fd=156, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 8899, 0, 0), raddr=('::1', 54340, 0, 0)> (FD 156) is already registered"
```

Because `TimeoutExpired` exception was not handled, `proxy.py` goes onto re-registering plain socket again resulting into `KeyError`.

**Expected behavior**
`proxy.py` must retry `openssl` command or bail out with server error.

**Comment by abhinavsingh** [comment]
Fixed in https://github.com/abhinavsingh/proxy.py/pull/388
