### ISSUE TITLE
What ‘CacheResponsesPlugin ' saved file is format?

### ISSUE THREAD

**Issue by tylk520** [abhinavsingh/proxy.py#399]
I think is gzip.
but
```
buf = io.BytesIO(file)
gf = gzip.GzipFile(fileobj = buf)
content = gf.read().decode('UTF-8')
```
is no work.

**Comment by abhinavsingh** [comment]
CacheResponsePlugin saves raw response from the server.  If you open the
response dump, you will see HTTP headers in plain text.  Though the HTTP
response content type itself can be gzip or chunked encoded etc depending
upon response headers.

**Comment by abhinavsingh** [comment]
Example, you can do something like this:

```bash
>>> from proxy.http.parser import HttpParser, httpParserTypes
>>> p = HttpParser(httpParserTypes.REQUEST_PARSER)
>>> with open('/var/folders/ry/tkb2qyj13qv1mdwf6z7r13l00000gn/T/httpbin.org-9c784a6b2e8741daab015e3855a245f5.txt', 'rb') as response:
...   r = response.read()
...   p.parse(r)
... 
```

Then, you can further decode response body as gzip based upon HTTP response headers.  To inspect HTTP response headers, simple:

```
>>> p.headers
{b'date': (b'Date', b'Sun, 12 Jul 2020 14:54:37 GMT'), b'content-type': (b'Content-Type', b'application/json'), b'content-length': (b'Content-Length', b'257'), b'connection': (b'Connection', b'keep-alive'), b'server': (b'Server', b'gunicorn/19.9.0'), b'access-control-allow-origin': (b'Access-Control-Allow-Origin', b'*'), b'access-control-allow-credentials': (b'Access-Control-Allow-Credentials', b'true')}
>>>
>>> p.header('content-type')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abhinavsingh/Dev/proxy.py/proxy/http/parser.py", line 86, in header
    raise KeyError('%s not found in headers', text_(key))
KeyError: ('%s not found in headers', 'content-type')
```

Example in my case above, there was no `content-type` header present in the response.

**Comment by abhinavsingh** [comment]
Feel free to re-open if you are having trouble parsing the response.  Thank you!!!
