### ISSUE TITLE
Docker cannot start reverse proxy

### ISSUE THREAD

**Issue by lubomirhadziev** [abhinavsingh/proxy.py#414]
When i try this

`docker run -it  --rm abhinavsingh/proxy.py:latest --enable-web-server --plugins proxy.plugin.ReverseProxyPlugin`

The output is:

```
2020-08-04 09:09:49,432 - pid:1 [I] load_plugins:534 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2020-08-04 09:09:49,433 - pid:1 [I] load_plugins:534 - Loaded plugin proxy.http.server.HttpWebServerPlugin
2020-08-04 09:09:49,434 - pid:1 [I] load_plugins:534 - Loaded plugin proxy.plugin.ReverseProxyPlugin
Traceback (most recent call last):
  File "/usr/local/bin/proxy", line 11, in <module>
    load_entry_point('proxy.py==2.2.0', 'console_scripts', 'proxy')()
  File "/usr/local/lib/python3.8/site-packages/proxy/proxy.py", line 89, in entry_point
    main(input_args=sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/proxy/proxy.py", line 80, in main
    with Proxy(input_args=input_args, **opts):
  File "/usr/local/lib/python3.8/site-packages/proxy/proxy.py", line 48, in __enter__
    self.acceptors.setup()
  File "/usr/local/lib/python3.8/site-packages/proxy/core/acceptor/pool.py", line 118, in setup
    self.listen()
  File "/usr/local/lib/python3.8/site-packages/proxy/core/acceptor/pool.py", line 58, in listen
    self.socket.bind((str(self.flags.hostname), self.flags.port))
OSError: [Errno 99] Address not available
```

**Comment by abhinavsingh** [comment]
@lubomirhadziev You must also pass `--hostname 0.0.0.0` flag.  Above you are overriding default `Docker` flags which include the `--hostname 0.0.0.0` flag.  In absence of this flag, `proxy.py` will try to listen on `::` IPv6.  Docker doesn't come with `IPv6` enabled by default.

**Comment by abhinavsingh** [comment]
Closing this for now.  Please re-open if `OSError: [Errno 99] Address not available` the problem persists.
