### ISSUE TITLE
Install proxy.py as non root

### ISSUE THREAD

**Issue by mbatrawi** [abhinavsingh/proxy.py#431]
non root gives me this error
how to fix

```
pip --user install --upgrade proxy.py        
Traceback (most recent call last):
  File "/usr/pkg/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
    for dist in factory(fullpath):
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
PermissionError: [Errno 13] Permission denied: '/sdf/sys/pkg6_amd64/lib/python3.6/site-packages/meson-0.54.2-py3.6.egg-info'
/sdf/arpa/gm/k/kata/master/proxy/>
```

**Comment by mbatrawi** [comment]
pip --user install --upgrade proxy.py        
Traceback (most recent call last):
  File "/usr/pkg/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
    for dist in factory(fullpath):
  File "/usr/pkg/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
PermissionError: [Errno 13] Permission denied: '/sdf/sys/pkg6_amd64/lib/python3.6/site-packages/meson-0.54.2-py3.6.egg-info'
/sdf/arpa/gm/k/kata/master/proxy/>

**Comment by Ishidres** [comment]
Have you tried using `pip3` instead of `pip`?

**Comment by abhinavsingh** [comment]
@mbatrawi You are trying to install `proxy.py` globally.  And looks like your global `site-packages` folder is under `/usr/pkg/lib` that you don't have direct permission.

I'll recommend to install `proxy.py` via `virtualenv`.  E.g.

```
❯ python3 -m venv venv
❯ source venv/bin/activate
❯ pip install proxy.py
```

**Comment by mbatrawi** [comment]
source not found

**Comment by abhinavsingh** [comment]
> source not found

thats odd.  You can also directly try `./venv/bin/pip install proxy.py`.  This will place `proxy.py` binary under ./venv/bin` folder.

**Comment by mbatrawi** [comment]
thanks
