### ISSUE TITLE
Listen on IPv6

### ISSUE THREAD

**Issue by limbo127** [abhinavsingh/proxy.py#48]
hello, 
how listen only on specifiq ipv6 address

```
python /tmp/proxy.py --hostname [fd00::8e2:97ff:fe2e:f1ea] --port 8081 --log-level DEBUG
2019-04-18 15:32:05,116 - INFO - run:633 - Starting server on port 8081
2019-04-18 15:32:05,125 - ERROR - run:643 - Exception while running the server gaierror(-2, 'Name or service not known')
Traceback (most recent call last):
  File "/tmp/proxy.py", line 636, in run
    self.socket.bind((self.hostname, self.port))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -2] Name or service not known
2019-04-18 15:32:05,126 - INFO - run:645 - Closing server socket
```

```
python /tmp/proxy.py --hostname fd00::8e2:97ff:fe2e:f1ea --port 8081 --log-level DEBUG
2019-04-18 15:32:17,082 - INFO - run:633 - Starting server on port 8081
2019-04-18 15:32:17,082 - ERROR - run:643 - Exception while running the server gaierror(-9, 'Address family for hostname not supported')
Traceback (most recent call last):
  File "/tmp/proxy.py", line 636, in run
    self.socket.bind((self.hostname, self.port))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -9] Address family for hostname not supported
2019-04-18 15:32:17,082 - INFO - run:645 - Closing server socket
```

**Comment by limbo127** [comment]
hello, 
how listen only on specifiq ipv6 address


python /tmp/proxy.py --hostname [fd00::8e2:97ff:fe2e:f1ea] --port 8081 --log-level DEBUG
2019-04-18 15:32:05,116 - INFO - run:633 - Starting server on port 8081
2019-04-18 15:32:05,125 - ERROR - run:643 - Exception while running the server gaierror(-2, 'Name or service not known')
Traceback (most recent call last):
  File "/tmp/proxy.py", line 636, in run
    self.socket.bind((self.hostname, self.port))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -2] Name or service not known
2019-04-18 15:32:05,126 - INFO - run:645 - Closing server socket

python /tmp/proxy.py --hostname fd00::8e2:97ff:fe2e:f1ea --port 8081 --log-level DEBUG
2019-04-18 15:32:17,082 - INFO - run:633 - Starting server on port 8081
2019-04-18 15:32:17,082 - ERROR - run:643 - Exception while running the server gaierror(-9, 'Address family for hostname not supported')
Traceback (most recent call last):
  File "/tmp/proxy.py", line 636, in run
    self.socket.bind((self.hostname, self.port))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -9] Address family for hostname not supported
2019-04-18 15:32:17,082 - INFO - run:645 - Closing server socket
