### ISSUE TITLE
Large multi-part upload fails

### ISSUE THREAD

**Issue by geyang** [abhinavsingh/proxy.py#512]
Thanks for this wonderful library and your dedication to all of these issues!

**Describe the bug**

I just have a quick question: I am trying to use a proxy to send data out of a walled-off cluster environment, but it looks like large payloads uploaded via multi-part form upload fails consistently. 

Here is the trace from the proxy, shall I just increase the `recv_buff` size for both the client and the receiving end?

```
2021-03-09 13:30:12,331 - pid:6168 [D] recv:65 - received 1048576 bytes from client
2021-03-09 13:30:12,409 - pid:6168 [D] handle_readables:251 - Client is ready for reads, reading
2021-03-09 13:30:12,410 - pid:6168 [D] recv:65 - received 864623 bytes from client
2021-03-09 13:30:12,489 - pid:6168 [D] connect_upstream:417 - Connecting to upstream blah:8080
2021-03-09 13:30:12,556 - pid:6168 [D] connect_upstream:422 - Connected to upstream blah:8080
2021-03-09 13:30:12,642 - pid:6168 [D] write_to_descriptors:157 - Server is write ready, flushing buffer
2021-03-09 13:30:12,803 - pid:6168 [D] flush:92 - flushed 16384 bytes to server
2021-03-09 13:30:12,804 - pid:6168 [D] write_to_descriptors:157 - Server is write ready, flushing buffer
2021-03-09 13:30:12,889 - pid:6168 [E] write_to_descriptors:170 - OSError when flushing buffer to server
Traceback (most recent call last):
  File "/home/gridsan/geyang/.local/lib/python3.7/site-packages/proxy/http/proxy/server.py", line 159, in write_to_descriptors
    self.server.flush()
  File "/home/gridsan/geyang/.local/lib/python3.7/site-packages/proxy/core/connection/connection.py", line 86, in flush
    sent: int = self.send(mv[:DEFAULT_MAX_SEND_SIZE])
  File "/home/gridsan/geyang/.local/lib/python3.7/site-packages/proxy/core/connection/connection.py", line 55, in send
    return self.connection.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-03-09 13:30:12,924 - pid:6168 [I] access_log:408 - some-blah:60214 - POST blah:8080/ - None None - 0 bytes - 9217.99 ms
2021-03-09 13:30:12,924 - pid:6168 [D] on_client_connection_close:264 - Closed server connection, has buffer True
2021-03-09 13:30:12,924 - pid:6168 [D] shutdown:176 - Closing client connection <socket.socket fd=145, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.31.130.226', 8081), raddr=('172.31.130.152', 60214)> at address ('172.31.130.152', 60214) has buffer False
2021-03-09 13:30:12,924 - pid:6168 [D] shutdown:184 - Client connection shutdown successful
2021-03-09 13:30:12,924 - pid:6168 [D] shutdown:189 - Client connection closed
```

**Comment by abhinavsingh** [comment]
Hi @geyang , I am wondering if these errors could be because of upstream server max upload size restrictions.  Example, does a direct upload (not via proxy.py) works on the server?

`some-blah:60214 - POST blah:8080/ - None None - 0 bytes - 9217.99 ms`
^^^ This indicated that a plugin is possibly trying to upload to a server

`Closed server connection, has buffer True`
^^^ Indicates that `proxy.py` had pending buffer for server.

`ConnectionResetError: [Errno 104] Connection reset by peer`
^^^ Indicates upstream server closed the connection.

**Comment by abhinavsingh** [comment]
@geyang Are you still experiencing this issue?

**Comment by geyang** [comment]
Hey @abhinavsingh you are right, this is not an issue with the proxy.py module. Your comment really helped with my debugging. Thanks a lot!!

**Comment by abhinavsingh** [comment]
Closing this now, feel free to re-open if problem persists.
