### ISSUE TITLE
SSL Error when using proxy certificate [ssl.SSLError]

### ISSUE THREAD

**Issue by hash3liZer** [abhinavsingh/proxy.py#529]
I've created self-signed certificates using `openssl` with this command: 
```bash
$ openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```

And then ran the `proxy.py` from within my python script like this: 
```
proxy.main([
            '--hostname', '127.0.0.1',
            '--port', '8988',
            '--cert-file', 'D:\\cert.pem',
            '--key-file', 'D:\\key.pem'
        ],
            plugins=[
                CustomPlugin
            ]
        )
```

However, when i try to establish connection over the certificate with curl like this, the connection fails: 
```powershell
$ curl.exe -x http://localhost:1234 --proxy-cacert "D:\cert.pem" https://www.google.com
```

And i receive this error on my `script.py` window:
```python
ssl.SSLErrorlobj.do_handshake()
Traceback (most recent call last):QUEST] https proxy request (_ssl.c:1108)
  File "C:\Users\hashliZer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\proxy\http\handler.py", line 345, in run
    self.initialize()t call last):
  File "C:\Users\hashliZer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\proxy\http\handler.py", line 91, in initialize
    conn = self.optionally_wrap_socket(self.client.connection)
  File "C:\Users\hashliZer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\proxy\http\handler.py", line 200, in optionally_wrap_socket
    conn = wrap_socket(conn, self.flags.keyfile, self.flags.certfile)
  File "C:\Users\hashliZer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\proxy\common\utils.py", line 163, in wrap_socketwrap_socket
    return ctx.wrap_socket(, self.flags.keyfile, self.flags.certfile)
  File "C:\Users\hashliZer\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 500, in wrap_socketpy", line 163, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\hashliZer\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1040, in _createket
    self.do_handshake()et_class._create(
  File "C:\Users\hashliZer\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTPS_PROXY_REQUEST] https proxy request (_ssl.c:1108)sl.py", line 1309, in do_handshake
```

Operating System: `Windows`
Python Version: '3.8'

**Comment by abhinavsingh** [comment]
```
proxy.main([
            '--hostname', '127.0.0.1',
            '--port', '8988',
            '--cert-file', 'D:\\cert.pem',
            '--key-file', 'D:\\key.pem'
        ],
            plugins=[
                CustomPlugin
            ]
        )
```

This will start `proxy.py` in `HTTPS` mode a.k.a `HTTPS Proxy` where clients connect via `-x https://localhost:8899` and not `-x http://`

For interception, you need to pass the right flags.  See https://github.com/abhinavsingh/proxy.py#tls-interception
