### ISSUE TITLE
examples/https_connect_tunnel.py fails on Windows 10

### ISSUE THREAD

**Issue by skanga** [abhinavsingh/proxy.py#533]
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a bug report.

**Describe the bug**

**To Reproduce**
1. Run `proxy.py` as '...'
2. Do '...' to trigger error

**Expected behavior**

**Version information**
 - proxy.py Version [e.g. 1.1.1]

**Additional context**

**Screenshots**

**Comment by skanga** [comment]
Here is what I did

```
C:\Users\SKANGA\Downloads\proxy.py>set PYTHONPATH=.

C:\Users\SKANGA\Downloads\proxy.py>python examples/https_connect_tunnel.py
2021-04-06 18:32:47,168 - pid:83348 [I] load_plugins:334 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2021-04-06 18:32:47,170 - pid:83348 [I] listen:115 - Listening on ::1:12345
2021-04-06 18:32:47,216 - pid:83348 [I] start_workers:136 - Started 1 workers
Process Threadless-1:1:
Traceback (most recent call last):
  File "c:\bin\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\SKANGA\Downloads\proxy.py\proxy\core\acceptor\threadless.py", line 175, in run
    self.run_once()
  File "C:\Users\SKANGA\Downloads\proxy.py\proxy\core\acceptor\threadless.py", line 146, in run_once
    with self.selected_events() as (readables, writables):
  File "c:\bin\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\SKANGA\Downloads\proxy.py\proxy\core\acceptor\threadless.py", line 73, in selected_events
    ev = self.selector.select(timeout=1)
  File "c:\bin\Python37\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "c:\bin\Python37\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
2021-04-06 18:33:01,835 - pid:83348 [I] shutdown:153 - Shutting down 1 workers

C:\Users\SKANGA\Downloads\proxy.py>python -V
Python 3.7.8

```

**Comment by abhinavsingh** [comment]
Yes, this is related to https://github.com/abhinavsingh/proxy.py/issues/492 .  Here `https_connect_tunnel.py` example fails because it internally uses `threadless` mode.  If you have some bandwidth at your end, please give the proposed solution a try, see https://github.com/abhinavsingh/proxy.py/issues/492#issuecomment-769670047

**Comment by abhinavsingh** [comment]
I'll mark this as duplicate and close.  Let's resume discussion on #492
