### ISSUE TITLE
TLS Interception not capturing each request

### ISSUE THREAD

**Issue by hash3liZer** [abhinavsingh/proxy.py#590]
I am trying to intercept traffic through plugin from my browser. Proxy.py works all fine but not capturing everything. It is missing almost all the major requests. If i see on console, i see ssl wrap errors like this: 

```
OSError when wrapping client
Traceback (most recent call last):
  File "C:\Users\Shameer\AppData\Local\Programs\Python\Python39\lib\site-packages\proxy\http\proxy\server.py", line 529, in intercept
    self.wrap_client()
  File "C:\Users\Shameer\AppData\Local\Programs\Python\Python39\lib\site-packages\proxy\http\proxy\server.py", line 559, in wrap_client
    self.client.wrap(self.flags.ca_signing_key_file, generated_cert)
  File "C:\Users\Shameer\AppData\Local\Programs\Python\Python39\lib\site-packages\proxy\core\connection\client.py", line 37, in wrap
    self._conn = ssl.wrap_socket(
  File "C:\Users\Shameer\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "C:\Users\Shameer\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Shameer\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Shameer\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```

What's more strange is that even if these errors occurs, all the actual requests are send unmodified to the server. I am making this check in `close_connection` method like this: 

```
class Plugin:
    def close_connection(self):
        if self.request.host == b"mail.google.com":
            print("Request to google mail")
```

Now, when i open mail.google.com, i actually should see about atleast more than 10 requests to google but i only see one.

**Comment by hash3liZer** [comment]
Ok, after much research, i think its my bad. I wasn't able to capture the request using above code is because that the connection was still open. So, instead of capturing it in `close_connection`, i'd to capture it in: `handle_client_request`.
