### ISSUE TITLE
Teardown gracefully on MemoryError

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#66]
Reproducible by running `proxy.py` on smallest GCP instance _(or a system with <500Mb of free RAM)_ and stress testing it via fast.com speed tests.

```
Traceback (most recent call last):
File "./proxy.py", line 1082, in run
  teardown = self.run_once()
File "./proxy.py", line 1067, in run_once
  teardown = plugin.read_from_descriptors(readable)
File "/home/mailsforabhinav/proxy.py/proxy.py", line 834, in read_from_descriptors
  self.response.bytes += raw
MemoryError
```

**Comment by abhinavsingh** [comment]
Marking as enhancement / feature request since this is not a disruptive bug.
