### ISSUE TITLE
Hello All, 

### ISSUE THREAD

**Issue by sdenisen** [abhinavsingh/proxy.py#8]
Use the proxy.py library.
python 2.7 
the proxy successfully started via Pycharm with parameters, host:port: localhost:8890
From any browsers proxy-process stopped and raised the following exception, where I'm wrong?:
016-01-04 23:44:44,589 - INFO - pid:10340 - Starting server on hostname localhost and port 8890
2016-01-04 23:44:49,150 - DEBUG - pid:10340 - Accepted connection <socket._socketobject object at 0x024154C8> at address ('127.0.0.1', 61650)
2016-01-04 23:44:49,164 - ERROR - pid:10340 - Exception while running the server PicklingError("Can't pickle <built-in method recvfrom_into of _socket.socket object at 0x024EA440>: it's not found as **main**.recvfrom_into",)
Traceback (most recent call last):
  File "C:/Program Files (x86)/Python27/Lib/site-packages/proxy.py", line 529, in run
    self.handle(client)
  File "C:/Program Files (x86)/Python27/Lib/site-packages/proxy.py", line 545, in handle
    proc.start()
  File "C:\Program Files (x86)\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Program Files (x86)\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Program Files (x86)\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 548, in save_tuple
    save(element)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files (x86)\Python27\lib\pickle.py", line 748, in save_global
    (obj, module, name))
PicklingError: Can't pickle <built-in method recvfrom_into of _socket.socket object at 0x024EA440>: it's not found as __main__.recvfrom_into
2016-01-04 23:44:49,167 - INFO - pid:10340 - Closing server socket

**Comment by alvarudras** [comment]
Hi, If you havent solved this issue, then -
import threading
and then replace line
class Proxy(multiprocessing.Process):
with this
class Proxy(threading.Thread):

see if that solves the issue

**Comment by sdenisen** [comment]
thanks, it helped me

**Comment by abhinavsingh** [comment]
https://github.com/abhinavsingh/proxy.py/commit/d26b61111dbc6c32c90b180135be61a29f0d990a should address the same. Thank You!!!
