### ISSUE TITLE
Connection remains in TIME_WAIT states after passing to Worker process

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#97]
Reproducible using simple stress testing:

```
Process Worker-8:
2019-09-25 18:41:58,202 - INFO - pid:59978 - access_log:1290 - ::1:54155 - GET /accounts.zip
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "./proxy.py", line 487, in run
    teardown = self.run_once()
  File "./proxy.py", line 448, in run_once
    fileno = recv_handle(self.work_queue)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/reduction.py", line 153, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
OSError: [Errno 40] Message too long
```

Example:

`$ proxy.py --enable-web-server`

Get parent pid from printed logs and monitor for open files per process:

`$ PPID=24451; while true; do for pid in $(pgrep -P $PPID); do lsof -p $pid | wc -l; done; echo; sleep 5; done`

On multiple terminals simply start:

`while true; do curl http://localhost:8899/; done`

Over time, number of open files per worker process keeps on increasing, eventually resulting in `OSError: [Errno 40] Message too long` when open files are more than set limit.

Inspection for one of the worker process revealed `483` connections are in `CLOSED` state and `417` in `TIME_WAIT`.

```
Python  12998 abhinav    8u  IPv6 0x10775da83860a9cd       0t0        TCP localhost:8899->localhost:62036 (CLOSED)
Python  12998 abhinav    9u  IPv6 0x10775da83a6ad9cd       0t0        TCP localhost:8899->localhost:62044 (CLOSED)
Python  12998 abhinav   10u  IPv6 0x10775da83a71eb0d       0t0        TCP localhost:8899->localhost:62052 (CLOSED)
.... [ several CLOSED ]
.... [ hundreds of TIME_WAIT ]
Python  12998 abhinav  770u  IPv6 0x10775da856d952cd       0t0        TCP localhost:8899->localhost:51755 (TIME_WAIT)
Python  12998 abhinav  771u  IPv6 0x10775da856da2e4d       0t0        TCP localhost:8899->localhost:51763 (TIME_WAIT)
Python  12998 abhinav  772u  IPv6 0x10775da856dacf8d       0t0        TCP localhost:8899->localhost:51771 (TIME_WAIT)
Python  12998 abhinav  773u  IPv6 0x10775da856db374d       0t0        TCP localhost:8899->localhost:51779 (TIME_WAIT)
Python  12998 abhinav  774u  IPv6 0x10775da856dc29cd       0t0        TCP localhost:8899->localhost:51787 (TIME_WAIT)
Python  12998 abhinav  775u  IPv6 0x10775da856dcb74d       0t0        TCP localhost:8899->localhost:51795 (TIME_WAIT)
Python  12998 abhinav  776u  IPv6 0x10775da856dcdf8d       0t0        TCP localhost:8899->localhost:51803 (TIME_WAIT)
```

**Comment by abhinavsingh** [comment]
This should be resolvable by customizing `Maximum Segment Lifetime` on the operating system so that closed sockets are immediately available for new client connections.  Don't think `proxy.py` can do something to handle this at its level.

**Comment by abhinavsingh** [comment]
Using following code to replicate the scenario by placing it at different workflows:

```
logger.debug('closing')
client.connection.setsockopt(socket.SOL_SOCKET, socket.SO_LINGER, struct.pack('ii', 1, 0))
client.connection.recv(1024)
client.connection.send(b'HTTP/1.1 200 OK\r\nConnection: close\r\n\r\n')
client.connection.shutdown(socket.SHUT_RDWR)
client.connection.close()
```

Put above code under:

1. WorkerPool.handle

    Connection is closed here within the main thread context, never passed to a worker process.  `lsof` reveals that connection is closed after `curl` finishes.

2. Worker.run_once

    Connection here is closed within the context of worker process. `lsof` here reveals that connection is held in TIME_WAIT state.
